import { useEffect, useState, type FormEvent } from 'react'
import { X } from 'lucide-react'
import type { ShoppingItem, ShoppingItemInput } from '../types'

const categories = ['Warzywa i owoce', 'Nabiał', 'Pieczywo', 'Mięso i ryby', 'Napoje', 'Słodycze', 'Chemia', 'Dom', 'Apteka', 'Inne']
const units = ['szt.', 'kg', 'g', 'l', 'ml', 'opak.', 'but.', 'pusz.']
interface Props { familyId: string; listId: string; item?: ShoppingItem | null; saving: boolean; onSave: (input: ShoppingItemInput, id?: string) => Promise<void>; onClose: () => void }
export function ShoppingItemModal({ familyId, listId, item, saving, onSave, onClose }: Props) {
  const [name, setName] = useState(item?.name ?? ''); const [quantity, setQuantity] = useState(item?.quantity?.toString() ?? ''); const [unit, setUnit] = useState(item?.unit ?? ''); const [category, setCategory] = useState(item?.category ?? ''); const [note, setNote] = useState(item?.note ?? ''); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !saving) onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose, saving])
  async function submit(event: FormEvent) { event.preventDefault(); const parsed = quantity ? Number(quantity.replace(',', '.')) : null; if (parsed !== null && (!Number.isFinite(parsed) || parsed <= 0)) return setError('Ilość musi być większa od zera.'); setError(null); try { await onSave({ familyId, listId, name, quantity: parsed, unit, category, note }, item?.id); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Nie udało się zapisać produktu.') } }
  const field = 'mt-1.5 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm outline-none focus:border-brand-gold/40'
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-black/75 backdrop-blur-sm sm:place-items-center sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="shopping-item-modal-title" className="surface max-h-[92vh] w-full overflow-y-auto rounded-t-3xl p-5 sm:max-w-xl sm:rounded-3xl sm:p-6"><header className="flex justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-brand-gold">Szybkie dodawanie</p><h2 id="shopping-item-modal-title" className="mt-1 text-xl font-semibold">{item ? 'Edytuj produkt' : 'Dodaj produkt'}</h2></div><button type="button" disabled={saving} onClick={onClose} aria-label="Zamknij" className="rounded-xl p-2 text-brand-muted hover:bg-white/5 disabled:opacity-40"><X className="h-5 w-5"/></button></header><form onSubmit={(event) => void submit(event)} className="mt-5 space-y-4"><label className="block text-sm text-brand-muted">Nazwa produktu *<input autoFocus required maxLength={200} disabled={saving} value={name} onChange={(event) => setName(event.target.value)} className={field}/></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm text-brand-muted">Ilość<input inputMode="decimal" disabled={saving} value={quantity} onChange={(event) => setQuantity(event.target.value)} className={field}/></label><label className="block text-sm text-brand-muted">Jednostka<input list="shopping-units" maxLength={30} disabled={saving} value={unit} onChange={(event) => setUnit(event.target.value)} className={field}/><datalist id="shopping-units">{units.map((value) => <option key={value} value={value}/>)}</datalist></label></div><label className="block text-sm text-brand-muted">Kategoria<input list="shopping-categories" maxLength={50} disabled={saving} value={category} onChange={(event) => setCategory(event.target.value)} className={field}/><datalist id="shopping-categories">{categories.map((value) => <option key={value} value={value}/>)}</datalist></label><label className="block text-sm text-brand-muted">Notatka <span className="text-white/35">(opcjonalnie)</span><textarea rows={3} disabled={saving} value={note} onChange={(event) => setNote(event.target.value)} className={field}/></label>{error ? <p role="alert" className="rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-sm text-red-300">{error}</p> : null}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={saving} onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-brand-muted">Anuluj</button><button disabled={saving} className="rounded-xl bg-brand-gold px-5 py-2.5 text-sm font-semibold text-black disabled:cursor-wait disabled:opacity-60">{saving ? 'Zapisywanie…' : 'Zapisz produkt'}</button></div></form></section></div>
}
