import { useEffect, useMemo, useRef, useState } from 'react'
import { Archive, ArchiveRestore, ListFilter, Pencil, Plus, ShoppingCart, Trash2 } from 'lucide-react'
import type { FamilyContext } from '../../../types/domain'
import { canCreateShoppingList, canManageShoppingList, filterShoppingItems, shoppingCounts, sortShoppingItems } from '../shopping-utils'
import type { ShoppingFilter, ShoppingItem, ShoppingItemInput, ShoppingList, ShoppingListInput } from '../types'
import { useShopping } from '../hooks/useShopping'
import { DeleteShoppingItemModal } from './DeleteShoppingItemModal'
import { DeleteShoppingListModal } from './DeleteShoppingListModal'
import { ShoppingItemModal } from './ShoppingItemModal'
import { ShoppingItemRow } from './ShoppingItemRow'
import { ShoppingListModal } from './ShoppingListModal'
import { ShoppingListSelector } from './ShoppingListSelector'
import { useNativeBackDismiss } from '../../../app/native-platform'

const filters: Array<{ value: ShoppingFilter; label: string }> = [{ value: 'all', label: 'Wszystkie' }, { value: 'unpurchased', label: 'Do kupienia' }, { value: 'purchased', label: 'Kupione' }, { value: 'mine', label: 'Moje' }]
interface Props { family: FamilyContext; quickAddRequest: number }

export function ShoppingView({ family, quickAddRequest }: Props) {
  const shopping = useShopping(family.familyId)
  const [showArchived, setShowArchived] = useState(false); const [filter, setFilter] = useState<ShoppingFilter>('all'); const [category, setCategory] = useState('')
  const [listEditor, setListEditor] = useState<ShoppingList | 'new' | null>(null); const [itemEditor, setItemEditor] = useState<ShoppingItem | 'new' | null>(null)
  const [deleteList, setDeleteList] = useState<ShoppingList | null>(null); const [deleteItem, setDeleteItem] = useState<ShoppingItem | null>(null)
  const handledRequest = useRef(quickAddRequest); const canCreateList = canCreateShoppingList(family.role)
  useEffect(() => { if (quickAddRequest !== handledRequest.current) { handledRequest.current = quickAddRequest; if (shopping.selectedList && !shopping.selectedList.isArchived) setItemEditor('new'); else if (canCreateList) setListEditor('new') } }, [canCreateList, quickAddRequest, shopping.selectedList])
  const categories = useMemo(() => [...new Set(shopping.items.map((item) => item.category).filter((value): value is string => Boolean(value)))].sort(), [shopping.items])
  const visibleItems = useMemo(() => sortShoppingItems(filterShoppingItems(shopping.items, filter, family.userId, category)), [category, family.userId, filter, shopping.items])
  const unpurchased = visibleItems.filter((item) => !item.isPurchased); const purchased = visibleItems.filter((item) => item.isPurchased); const counts = shoppingCounts(shopping.items)
  const canManageList = shopping.selectedList ? canManageShoppingList(shopping.selectedList, family.userId, family.role) : false
  useNativeBackDismiss(Boolean(deleteList || deleteItem || itemEditor || listEditor), () => { if (deleteList) setDeleteList(null); else if (deleteItem) setDeleteItem(null); else if (itemEditor) setItemEditor(null); else setListEditor(null) })
  async function saveList(input: ShoppingListInput, id?: string) { if (id) await shopping.updateList(id, input); else await shopping.createList(input) }
  async function saveItem(input: ShoppingItemInput, id?: string) { if (id) await shopping.updateItem(id, input); else await shopping.createItem(input) }

  if (shopping.loadingLists) return <div className="mx-auto max-w-[1500px] p-3 sm:p-4 md:p-7"><div className="surface h-[32rem] animate-pulse rounded-2xl" aria-label="Ładowanie list zakupów"/></div>
  if (shopping.error) return <div className="mx-auto max-w-[1500px] p-3 sm:p-4 md:p-7"><p role="alert" className="surface rounded-2xl p-4 text-red-300 sm:p-5">Nie udało się pobrać zakupów: {shopping.error}</p></div>

  return <div className="mx-auto min-w-0 max-w-[1500px] overflow-x-clip p-3 sm:p-4 md:p-7">
    <header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end sm:gap-4"><div><p className="mb-1 text-xs uppercase tracking-[.16em] text-brand-gold sm:tracking-[.18em]">{family.familyName}</p><h1 className="text-2xl font-semibold md:text-3xl">Lista zakupów</h1><p className="mt-1 text-sm text-brand-muted">Wiele rodzinnych list, wspólne dodawanie i wygodne zakupy.</p></div>{canCreateList ? <button type="button" onClick={() => setListEditor('new')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-brand-gold/25 px-4 py-2 text-sm text-brand-gold"><Plus className="h-4 w-4"/>Nowa lista</button> : null}</header>
    {shopping.actionError ? <p role="alert" className="mt-3 rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-sm text-red-300 sm:mt-4">{shopping.actionError}</p> : null}
    {shopping.lists.length === 0 ? <section className="surface mt-4 rounded-2xl p-8 text-center sm:mt-6 sm:p-10"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-brand-gold/10 text-brand-gold"><ShoppingCart className="h-7 w-7"/></div><h2 className="mt-4 text-lg font-semibold">Nie masz jeszcze żadnej listy zakupów.</h2><p className="mt-2 text-sm text-brand-muted">{canCreateList ? 'Utwórz pierwszą listę i zacznij dodawać produkty.' : 'Poproś dorosłego o utworzenie listy.'}</p>{canCreateList ? <button type="button" onClick={() => setListEditor('new')} className="mt-5 min-h-11 rounded-xl bg-brand-gold px-5 py-2 text-sm font-semibold text-black">Utwórz pierwszą listę</button> : null}</section> : <div className="mt-3.5 grid min-w-0 gap-2.5 sm:mt-6 sm:gap-4 lg:grid-cols-[260px_1fr]">
      <ShoppingListSelector lists={shopping.lists} selectedId={shopping.selectedListId} showArchived={showArchived} onSelect={shopping.selectList} onShowArchived={setShowArchived}/>
      <main className="min-w-0">{shopping.selectedList ? <>
        <section className="surface rounded-2xl p-2 sm:p-5"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-start sm:gap-4"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-sm font-semibold leading-tight sm:text-xl">{shopping.selectedList.name}</h2>{shopping.selectedList.isArchived ? <span className="shrink-0 rounded-full bg-white/5 px-2 py-1 text-[9.5px] text-brand-muted">Archiwalna</span> : null}</div>{shopping.selectedList.description ? <p className="mobile-secondary mt-0.5 text-brand-muted sm:text-sm">{shopping.selectedList.description}</p> : null}<p className="mobile-metadata mt-0.5 text-brand-muted/90 sm:mt-2 sm:text-xs">{counts.unpurchased} do kupienia • {counts.purchased} kupione</p></div><div className="flex min-w-0 flex-nowrap items-center gap-0.5 sm:gap-2">{!shopping.selectedList.isArchived ? <button type="button" onClick={() => setItemEditor('new')} className="flex h-11 min-w-0 flex-1 items-center justify-center p-0 sm:flex-none"><span className="inline-flex h-10 w-full items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-brand-gold px-3 text-[13px] font-semibold text-black sm:gap-2 sm:px-4 sm:text-sm"><Plus className="h-4 w-4 shrink-0"/><span className="truncate">Dodaj produkt</span></span></button> : null}{canManageList ? <><button type="button" onClick={() => setListEditor(shopping.selectedList)} aria-label="Edytuj listę" className="grid h-11 w-11 shrink-0 place-items-center"><span className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.08] text-brand-muted"><Pencil className="h-4 w-4"/></span></button><button type="button" onClick={() => void shopping.archiveList(shopping.selectedList!.id, !shopping.selectedList!.isArchived).catch(() => undefined)} aria-label={shopping.selectedList.isArchived ? 'Przywróć listę' : 'Archiwizuj listę'} className="grid h-11 w-11 shrink-0 place-items-center"><span className="grid h-9 w-9 place-items-center rounded-lg border border-white/[.08] text-brand-muted">{shopping.selectedList.isArchived ? <ArchiveRestore className="h-4 w-4"/> : <Archive className="h-4 w-4"/>}</span></button><button type="button" onClick={() => setDeleteList(shopping.selectedList)} aria-label="Usuń listę" className="grid h-11 w-11 shrink-0 place-items-center"><span className="grid h-9 w-9 place-items-center rounded-lg border border-red-400/10 text-red-300"><Trash2 className="h-4 w-4"/></span></button></> : null}</div></div></section>
        <section className="mt-2 flex min-w-0 flex-col gap-1.5 sm:mt-4 sm:flex-row sm:items-center sm:gap-3"><div className="scrollbar-none -mx-0.5 flex min-w-0 flex-nowrap gap-1 overflow-x-auto px-0.5" role="group" aria-label="Filtry produktów">{filters.map((value) => <button key={value.value} type="button" aria-pressed={filter === value.value} onClick={() => setFilter(value.value)} className={`h-7 shrink-0 whitespace-nowrap rounded-full border px-2.5 text-xs ${filter === value.value ? 'border-brand-gold/15 bg-brand-gold/85 text-black' : 'border-white/[.06] bg-black/10 text-brand-muted/85'}`}>{value.label}</button>)}</div>{categories.length ? <label className="flex min-w-0 items-center gap-2 text-xs text-brand-muted"><ListFilter className="h-4 w-4 shrink-0"/><select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-10 min-w-0 rounded-xl border border-white/10 bg-[#101017] px-3 py-2"><option value="">Wszystkie kategorie</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label> : null}</section>
        {shopping.loadingItems ? <div className="surface mt-2 h-72 animate-pulse rounded-2xl sm:mt-4" aria-label="Ładowanie produktów"/> : visibleItems.length === 0 ? <div className="surface mt-2 rounded-2xl p-7 text-center sm:mt-4 sm:p-9"><p className="font-medium">Brak produktów dla tego filtra.</p><p className="mt-1 text-sm text-brand-muted">Dodaj produkt lub wybierz inny filtr.</p></div> : <div className="mt-2 grid min-w-0 items-start gap-2 sm:mt-4 sm:gap-4 xl:grid-cols-2"><section className="surface min-w-0 rounded-xl p-1.5 sm:rounded-2xl sm:p-3"><h3 className="px-1 py-0.5 text-[10.5px] font-semibold uppercase tracking-[.08em] text-brand-gold sm:px-2 sm:py-2 sm:text-xs sm:tracking-[.16em]">Do kupienia ({unpurchased.length})</h3><div className="space-y-1 sm:space-y-3">{unpurchased.length ? unpurchased.map((item) => <ShoppingItemRow key={item.id} item={item} userId={family.userId} role={family.role} updating={shopping.updatingIds.has(item.id)} onToggle={(value) => void shopping.togglePurchased(value)} onEdit={setItemEditor} onDelete={setDeleteItem}/>) : <p className="py-6 text-center text-xs text-brand-muted sm:py-8">Wszystko kupione.</p>}</div></section><section className="surface min-w-0 rounded-xl p-1.5 sm:rounded-2xl sm:p-3"><h3 className="px-1 py-0.5 text-[10.5px] font-semibold uppercase tracking-[.08em] text-brand-green sm:px-2 sm:py-2 sm:text-xs sm:tracking-[.16em]">Kupione ({purchased.length})</h3><div className="space-y-1 sm:space-y-3">{purchased.length ? purchased.map((item) => <ShoppingItemRow key={item.id} item={item} userId={family.userId} role={family.role} updating={shopping.updatingIds.has(item.id)} onToggle={(value) => void shopping.togglePurchased(value)} onEdit={setItemEditor} onDelete={setDeleteItem}/>) : <p className="py-6 text-center text-xs text-brand-muted sm:py-8">Brak kupionych produktów.</p>}</div></section></div>}
      </> : <div className="surface rounded-2xl p-8 text-center text-sm text-brand-muted">Włącz „Pokaż archiwalne” lub wybierz aktywną listę.</div>}</main>
    </div>}
    {listEditor ? <ShoppingListModal familyId={family.familyId} list={listEditor === 'new' ? null : listEditor} saving={shopping.saving} onSave={saveList} onClose={() => setListEditor(null)}/> : null}
    {itemEditor && shopping.selectedList ? <ShoppingItemModal familyId={family.familyId} listId={shopping.selectedList.id} item={itemEditor === 'new' ? null : itemEditor} saving={shopping.saving} onSave={saveItem} onClose={() => setItemEditor(null)}/> : null}
    {deleteItem ? <DeleteShoppingItemModal item={deleteItem} deleting={shopping.deletingIds.has(deleteItem.id)} onDelete={shopping.deleteItem} onClose={() => setDeleteItem(null)}/> : null}
    {deleteList ? <DeleteShoppingListModal list={deleteList} deleting={shopping.deletingIds.has(deleteList.id)} onDelete={shopping.deleteList} onClose={() => setDeleteList(null)}/> : null}
  </div>
}
