import { Check, Pencil, Trash2, UserRound } from 'lucide-react'
import type { FamilyRole } from '../../../types/domain'
import { canDeleteShoppingItem, canEditShoppingItem, formatQuantity } from '../shopping-utils'
import type { ShoppingItem } from '../types'

interface Props { item: ShoppingItem; userId: string; role: FamilyRole; updating: boolean; onToggle: (item: ShoppingItem) => void; onEdit: (item: ShoppingItem) => void; onDelete: (item: ShoppingItem) => void }
export function ShoppingItemRow({ item, userId, role, updating, onToggle, onEdit, onDelete }: Props) {
  const canEdit = canEditShoppingItem(item, userId, role); const canDelete = canDeleteShoppingItem(item, userId, role); const quantity = formatQuantity(item.quantity, item.unit)
  return <article className={`rounded-2xl border border-white/[.06] bg-black/15 p-2.5 sm:p-4 ${item.isPurchased ? 'opacity-60' : ''}`}><div className="flex items-start gap-1.5 sm:gap-3"><button type="button" disabled={updating} onClick={() => onToggle(item)} aria-label={item.isPurchased ? `Cofnij kupienie: ${item.name}` : `Oznacz jako kupione: ${item.name}`} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl disabled:cursor-wait"><span className={`grid h-7 w-7 place-items-center rounded-lg border transition ${item.isPurchased ? 'border-brand-green bg-brand-green text-black' : 'border-white/20 bg-black/15 hover:border-brand-gold/50'}`}>{updating ? <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-t-transparent"/> : item.isPurchased ? <Check className="h-[18px] w-[18px]"/> : null}</span></button><div className="min-w-0 flex-1"><div className="flex min-w-0 items-start justify-between"><h3 className={`min-w-0 break-words pt-1 font-medium leading-tight ${item.isPurchased ? 'line-through' : ''}`}>{item.name}</h3><div className="flex shrink-0">{canEdit ? <button type="button" onClick={() => onEdit(item)} aria-label={`Edytuj produkt: ${item.name}`} className="grid h-10 w-10 place-items-center rounded-xl text-brand-muted/90 hover:bg-white/5 hover:text-brand-gold"><Pencil className="h-[18px] w-[18px]"/></button> : null}{canDelete ? <button type="button" onClick={() => onDelete(item)} aria-label={`Usuń produkt: ${item.name}`} className="grid h-10 w-10 place-items-center rounded-xl text-brand-muted/90 hover:bg-red-400/10 hover:text-red-300"><Trash2 className="h-[18px] w-[18px]"/></button> : null}</div></div><div className="mt-0.5 flex flex-wrap gap-1 text-[11px] text-brand-muted/85">{quantity ? <span className="rounded-full bg-white/[.04] px-2 py-0.5">{quantity}</span> : null}{item.category ? <span className="rounded-full bg-brand-gold/[.08] px-2 py-0.5 text-brand-gold/90">{item.category}</span> : null}</div>{item.note ? <p className="mt-1 text-sm leading-snug text-brand-muted/90">{item.note}</p> : null}<div className="mt-1.5 flex flex-wrap gap-x-2.5 gap-y-0.5 text-[11px] leading-tight text-brand-muted/80"><span className="inline-flex items-center gap-1"><UserRound className="h-3 w-3"/>Dodał(a): {item.createdBy.displayName}</span>{item.isPurchased ? <span className="text-brand-green/90">Kupił(a): {item.purchasedBy?.displayName ?? 'użytkownik'}{item.purchasedAt ? ` • ${new Intl.DateTimeFormat('pl-PL', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(item.purchasedAt))}` : ''}</span> : null}</div></div></div></article>
}
