import { useEffect, useState, type FormEvent } from 'react'
import { X } from 'lucide-react'
import type { ShoppingList, ShoppingListInput } from '../types'

interface Props { familyId: string; list?: ShoppingList | null; saving: boolean; onSave: (input: ShoppingListInput, id?: string) => Promise<void>; onClose: () => void }
export function ShoppingListModal({ familyId, list, saving, onSave, onClose }: Props) {
  const [name, setName] = useState(list?.name ?? ''); const [description, setDescription] = useState(list?.description ?? ''); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !saving) onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose, saving])
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); try { await onSave({ familyId, name, description }, list?.id); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Nie udało się zapisać listy.') } }
  const field = 'mt-1.5 w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2.5 text-sm outline-none focus:border-brand-gold/40'
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-black/75 backdrop-blur-sm sm:place-items-center sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="shopping-list-modal-title" className="surface w-full rounded-t-3xl p-5 sm:max-w-lg sm:rounded-3xl sm:p-6"><header className="flex justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-brand-gold">Zakupy</p><h2 id="shopping-list-modal-title" className="mt-1 text-xl font-semibold">{list ? 'Edytuj listę' : 'Nowa lista zakupów'}</h2></div><button type="button" disabled={saving} onClick={onClose} aria-label="Zamknij" className="rounded-xl p-2 text-brand-muted hover:bg-white/5 disabled:opacity-40"><X className="h-5 w-5"/></button></header><form onSubmit={(event) => void submit(event)} className="mt-5 space-y-4"><label className="block text-sm text-brand-muted">Nazwa *<input autoFocus required maxLength={100} disabled={saving} value={name} onChange={(event) => setName(event.target.value)} className={field}/></label><label className="block text-sm text-brand-muted">Opis <span className="text-white/35">(opcjonalnie)</span><textarea rows={3} disabled={saving} value={description} onChange={(event) => setDescription(event.target.value)} className={field}/></label>{error ? <p role="alert" className="rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-sm text-red-300">{error}</p> : null}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={saving} onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-brand-muted">Anuluj</button><button disabled={saving} className="rounded-xl bg-brand-gold px-5 py-2.5 text-sm font-semibold text-black disabled:cursor-wait disabled:opacity-60">{saving ? 'Zapisywanie…' : list ? 'Zapisz zmiany' : 'Utwórz listę'}</button></div></form></section></div>
}
