import { Check, Pencil, Trash2, UserRound } from 'lucide-react'
import type { FamilyRole } from '../../../types/domain'
import { canDeleteShoppingItem, canEditShoppingItem, formatQuantity } from '../shopping-utils'
import type { ShoppingItem } from '../types'

interface Props { item: ShoppingItem; userId: string; role: FamilyRole; updating: boolean; onToggle: (item: ShoppingItem) => void; onEdit: (item: ShoppingItem) => void; onDelete: (item: ShoppingItem) => void }
export function ShoppingItemRow({ item, userId, role, updating, onToggle, onEdit, onDelete }: Props) {
  const canEdit = canEditShoppingItem(item, userId, role); const canDelete = canDeleteShoppingItem(item, userId, role); const quantity = formatQuantity(item.quantity, item.unit)
  return <article className={`rounded-2xl border border-white/[.07] bg-black/20 p-3 sm:p-4 ${item.isPurchased ? 'opacity-60' : ''}`}><div className="flex items-start gap-2 sm:gap-3"><button type="button" disabled={updating} onClick={() => onToggle(item)} aria-label={item.isPurchased ? `Cofnij kupienie: ${item.name}` : `Oznacz jako kupione: ${item.name}`} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl disabled:cursor-wait"><span className={`grid h-7 w-7 place-items-center rounded-lg border transition ${item.isPurchased ? 'border-brand-green bg-brand-green text-black' : 'border-white/25 bg-black/20 hover:border-brand-gold/60'}`}>{updating ? <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-t-transparent"/> : item.isPurchased ? <Check className="h-[18px] w-[18px]"/> : null}</span></button><div className="min-w-0 flex-1"><div className="flex min-w-0 items-start justify-between gap-1"><h3 className={`min-w-0 break-words pt-1 font-medium leading-snug ${item.isPurchased ? 'line-through' : ''}`}>{item.name}</h3><div className="flex shrink-0 gap-0.5">{canEdit ? <button type="button" onClick={() => onEdit(item)} aria-label={`Edytuj produkt: ${item.name}`} className="grid h-10 w-10 place-items-center rounded-xl text-brand-muted hover:bg-white/5 hover:text-brand-gold"><Pencil className="h-[18px] w-[18px]"/></button> : null}{canDelete ? <button type="button" onClick={() => onDelete(item)} aria-label={`Usuń produkt: ${item.name}`} className="grid h-10 w-10 place-items-center rounded-xl text-brand-muted hover:bg-red-400/10 hover:text-red-300"><Trash2 className="h-[18px] w-[18px]"/></button> : null}</div></div><div className="mt-1 flex flex-wrap gap-1.5 text-[11px] text-brand-muted">{quantity ? <span className="rounded-full bg-white/5 px-2 py-0.5">{quantity}</span> : null}{item.category ? <span className="rounded-full bg-brand-gold/10 px-2 py-0.5 text-brand-gold">{item.category}</span> : null}</div>{item.note ? <p className="mt-1.5 text-sm leading-snug text-brand-muted">{item.note}</p> : null}<div className="mt-2 flex flex-wrap gap-x-3 gap-y-0.5 text-[11px] leading-snug text-brand-muted"><span className="inline-flex items-center gap-1"><UserRound className="h-3 w-3"/>Dodał(a): {item.createdBy.displayName}</span>{item.isPurchased ? <span className="text-brand-green">Kupił(a): {item.purchasedBy?.displayName ?? 'użytkownik'}{item.purchasedAt ? ` • ${new Intl.DateTimeFormat('pl-PL', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(item.purchasedAt))}` : ''}</span> : null}</div></div></div></article>
}
