import{getSupabaseClient}from'../../../lib/supabase';import{centsToDatabase}from'../../budget/budget-utils';import type{ChargeDefinition,DefinitionInput,DefinitionUpdateInput,PaymentInput,Property,PropertyCharge,PropertyInput,PropertyUnit,UnitInput}from'../types'
const db=()=>{const c=getSupabaseClient();if(!c)throw new Error('Brak konfiguracji Supabase.');return c};const cents=(v:string|number|null)=>v===null?null:Math.round(Number(v)*100)
type PropertyRow={id:string;family_id:string;name:string;address:string|null;description:string|null;active:boolean}
type UnitRow={id:string;family_id:string;property_id:string;name:string;unit_type:PropertyUnit['type'];active:boolean}
type DefinitionRow={id:string;family_id:string;property_id:string;property_unit_id:string|null;name:string;category:ChargeDefinition['category'];amount_mode:ChargeDefinition['amountMode'];planned_amount:string|number|null;currency:string;recurrence_type:ChargeDefinition['recurrence'];recurrence_timezone:string;start_date:string;due_day:number|null;interval_months:number|null;recurrence_month:number|null;active:boolean;auto_generate:boolean;budget_sync_mode:ChargeDefinition['budgetSyncMode']}
type ChargeRow={id:string;family_id:string;property_id:string;property_unit_id:string|null;charge_definition_id:string;due_date:string;planned_amount:string|number|null;actual_amount:string|number|null;currency:string;status:PropertyCharge['status'];paid_at:string|null;notes:string|null;budget_transaction_id:string|null}
export function createPropertyRepository(){return{
 async ensure(familyId:string,start:string,end:string){const{error}=await db().rpc('ensure_property_charges',{target_family_id:familyId,range_start:start,range_end:end});if(error)throw new Error(error.message)},
 async properties(familyId:string){const{data,error}=await db().from('properties').select('id,family_id,name,address,description,active').eq('family_id',familyId).order('name');if(error)throw new Error(error.message);return(data??[]).map((r:PropertyRow):Property=>({id:r.id,familyId:r.family_id,name:r.name,address:r.address,description:r.description,active:r.active}))},
 async units(familyId:string){const{data,error}=await db().from('property_units').select('id,family_id,property_id,name,unit_type,active').eq('family_id',familyId).order('name');if(error)throw new Error(error.message);return(data??[]).map((r:UnitRow):PropertyUnit=>({id:r.id,familyId:r.family_id,propertyId:r.property_id,name:r.name,type:r.unit_type,active:r.active}))},
 async definitions(familyId:string){const{data,error}=await db().from('property_charge_definitions').select('id,family_id,property_id,property_unit_id,name,category,amount_mode,planned_amount,currency,recurrence_type,recurrence_timezone,start_date,due_day,interval_months,recurrence_month,active,auto_generate,budget_sync_mode').eq('family_id',familyId).order('name');if(error)throw new Error(error.message);return(data??[]).map((r:DefinitionRow):ChargeDefinition=>({id:r.id,familyId:r.family_id,propertyId:r.property_id,unitId:r.property_unit_id,name:r.name,category:r.category,amountMode:r.amount_mode,plannedAmountCents:cents(r.planned_amount),currency:r.currency,recurrence:r.recurrence_type,timezone:r.recurrence_timezone,startDate:r.start_date,dueDay:r.due_day,intervalMonths:r.interval_months,recurrenceMonth:r.recurrence_month,active:r.active,autoGenerate:r.auto_generate,budgetSyncMode:r.budget_sync_mode}))},
 async charges(familyId:string,start:string,end:string){const{data,error}=await db().from('property_charges').select('id,family_id,property_id,property_unit_id,charge_definition_id,due_date,planned_amount,actual_amount,currency,status,paid_at,notes,budget_transaction_id').eq('family_id',familyId).gte('due_date',start).lte('due_date',end).order('due_date');if(error)throw new Error(error.message);return(data??[]).map((r:ChargeRow):PropertyCharge=>({id:r.id,familyId:r.family_id,propertyId:r.property_id,unitId:r.property_unit_id,definitionId:r.charge_definition_id,dueDate:r.due_date,plannedAmountCents:cents(r.planned_amount),actualAmountCents:cents(r.actual_amount),currency:r.currency,status:r.status,paidAt:r.paid_at,notes:r.notes,budgetTransactionId:r.budget_transaction_id}))},
 async createProperty(i:PropertyInput){const{error}=await db().from('properties').insert({family_id:i.familyId,name:i.name,address:i.address||null,description:i.description||null});if(error)throw new Error(error.message)},
 async updateProperty(id:string,i:PropertyInput){const{error}=await db().from('properties').update({name:i.name,address:i.address||null,description:i.description||null}).eq('family_id',i.familyId).eq('id',id);if(error)throw new Error(error.message)},
 async createUnit(i:UnitInput){const{error}=await db().from('property_units').insert({family_id:i.familyId,property_id:i.propertyId,name:i.name,unit_type:i.type});if(error)throw new Error(error.message)},
 async createDefinition(i:DefinitionInput){const{error}=await db().rpc('create_property_charge_definition',{target_family_id:i.familyId,target_property_id:i.propertyId,target_unit_id:i.unitId,charge_name:i.name,charge_category:i.category,charge_amount_mode:i.amountMode,charge_planned_amount:i.plannedAmountCents===null?null:centsToDatabase(i.plannedAmountCents),charge_recurrence_type:i.recurrence,charge_timezone:i.timezone,charge_start_date:i.startDate,charge_due_day:i.dueDay,charge_interval_months:i.intervalMonths,charge_recurrence_month:i.recurrenceMonth,charge_selected_dates:i.selectedDates,charge_reminder_offsets:i.reminderOffsets,charge_auto_generate:i.autoGenerate,charge_budget_sync_mode:i.budgetSyncMode});if(error)throw new Error(error.message)},
 async updateDefinition(i:DefinitionUpdateInput){const{error}=await db().rpc('update_property_charge_definition',{target_family_id:i.familyId,target_definition_id:i.definitionId,target_property_id:i.propertyId,charge_name:i.name,charge_category:i.category,charge_amount_mode:i.amountMode,charge_planned_amount:i.plannedAmountCents===null?null:centsToDatabase(i.plannedAmountCents),charge_budget_sync_mode:i.budgetSyncMode});if(error)throw new Error(error.message)},
 async pay(i:PaymentInput){const{error}=await db().rpc('pay_property_charge',{target_family_id:i.familyId,target_charge_id:i.chargeId,paid_amount:centsToDatabase(i.amountCents),paid_timestamp:i.paidAt,payment_notes:i.notes,sync_budget:i.syncBudget});if(error)throw new Error(error.message)},
 async cancel(familyId:string,id:string){const{error}=await db().rpc('cancel_property_charge',{target_family_id:familyId,target_charge_id:id});if(error)throw new Error(error.message)},
 async archiveProperty(familyId:string,id:string){const{error}=await db().rpc('archive_property',{target_family_id:familyId,target_property_id:id});if(error)throw new Error(error.message)},
 async restoreProperty(familyId:string,id:string){const{error}=await db().rpc('restore_property',{target_family_id:familyId,target_property_id:id});if(error)throw new Error(error.message)},
 async deleteProperty(familyId:string,id:string){const{error}=await db().rpc('delete_property_permanently',{target_family_id:familyId,target_property_id:id});if(error)throw new Error(error.message)},
 async setDefinitionActive(familyId:string,id:string,active:boolean){const{error}=await db().rpc('set_property_charge_definition_active',{target_family_id:familyId,target_definition_id:id,next_active:active});if(error)throw new Error(error.message)}
}}
