import{readFileSync}from'node:fs'
import{resolve}from'node:path'
import{describe,expect,it}from'vitest'

const read=(path:string)=>readFileSync(resolve(process.cwd(),path),'utf8')
const migration=read('../../database/migrations/0024_delete_property_charge_definition.sql')
const historicalLifecycle=read('../../database/migrations/0019_property_charge_definition_lifecycle.sql')
const view=read('src/features/properties/components/PropertiesView.tsx')
const modal=read('src/features/properties/components/DeleteChargeDefinitionModal.tsx')
const repository=read('src/features/properties/api/property-repository.ts')
const hook=read('src/features/properties/hooks/useProperties.ts')

describe('0024 recurring charge permanent deletion',()=>{
  it('keeps deactivation as a separate reversible operation which does not delete history',()=>{const activation=historicalLifecycle.slice(historicalLifecycle.indexOf('function public.set_property_charge_definition_active'),historicalLifecycle.indexOf('create or replace function public.ensure_property_charges'));expect(activation).toContain('set active = next_active');expect(activation).not.toContain('delete from public.property_charges');expect(view).toContain("definition.active?'Dezaktywuj':'Aktywuj'")})
  it('exposes a separate owner/admin permanent-delete action',()=>{expect(view).toContain('setDeletingDefinition(definition)');expect(view).toContain('Usuń trwale');expect(view).toContain('{canDelete?');expect(repository).toContain("rpc('delete_property_charge_definition_permanently'");expect(hook).toContain('deleteDefinition:(id:string)')})
  it('requires confirmation and lets cancellation close without deletion',()=>{expect(modal).toContain('role="alertdialog"');expect(modal).toContain('Trwale usunąć opłatę cykliczną?');expect(modal).toContain('onClick={onClose}');expect(modal).toContain('Anuluj');expect(modal).toContain('Tej operacji nie można cofnąć.');expect(modal).toContain('if(inFlight.current)return')})
  it('deletes every generated occurrence including paid state and notes',()=>{expect(migration).toMatch(/delete from public\.property_charges[\s\S]*charge_definition_id = target_definition_id/);expect(migration).not.toMatch(/delete from public\.property_charges[\s\S]*status\s*=/);expect(migration).not.toMatch(/delete from public\.property_charges[\s\S]*notes\s*=/)})
  it('deletes only reminders and notifications sourced from matching occurrences',()=>{for(const table of ['public.notifications','public.reminders'])expect(migration).toMatch(new RegExp(`delete from ${table.replace('.','\\.')}[\\s\\S]*source_type = 'property_charge'[\\s\\S]*c\\.charge_definition_id = target_definition_id`));expect(migration).not.toMatch(/source_type\s*=\s*'(task|calendar_event)'/)})
  it('deletes definition-owned reminder rules and schedule configuration',()=>{expect(migration).toMatch(/delete from public\.property_charge_reminder_rules[\s\S]*definition_id = target_definition_id/);expect(migration).toMatch(/delete from public\.property_charge_schedule_dates[\s\S]*definition_id = target_definition_id/)})
  it('deletes only budget transactions explicitly linked by matching charges',()=>{expect(migration).toContain('pg_catalog.array_agg(distinct c.budget_transaction_id)');expect(migration).toMatch(/delete from public\.budget_transactions[\s\S]*family_id = target_family_id[\s\S]*id = any\(linked_budget_ids\)/);expect(migration).not.toMatch(/delete from public\.budget_transactions\s*;/)})
  it('does not delete the charge group or other recurring definitions',()=>{expect(migration).not.toContain('delete from public.properties');expect(migration).not.toContain('delete from public.property_units');expect(migration).toMatch(/delete from public\.property_charge_definitions[\s\S]*id = target_definition_id[\s\S]*family_id = target_family_id/)})
  it('rejects anonymous, unauthorized and cross-family requests before mutation',()=>{const permission=migration.indexOf('if not public.has_family_role');const lock=migration.indexOf('for update;');const firstDelete=migration.indexOf('delete from');expect(migration).toContain("if (select auth.uid()) is null");expect(migration).toContain("array['owner','admin']::public.family_role[]");expect(migration).toContain('where id = target_definition_id');expect(migration).toContain('and family_id = target_family_id');expect(permission).toBeLessThan(lock);expect(lock).toBeLessThan(firstDelete)})
  it('locks the definition and performs one atomic security-definer RPC',()=>{expect(migration).toContain('security definer');expect(migration).toContain("set search_path = ''");expect(migration).toContain('for update;');expect(migration).not.toMatch(/\bcommit\b|\brollback\b/i);expect(migration.match(/property\.charge_definition\.permanently_deleted/g)).toHaveLength(1)})
  it('does not grant broad delete access or private schema access',()=>{expect(migration).toContain('revoke all on function public.delete_property_charge_definition_permanently(uuid,uuid)');expect(migration).toContain('grant execute on function public.delete_property_charge_definition_permanently(uuid,uuid)');expect(migration).not.toMatch(/grant\s+delete/i);expect(migration).not.toMatch(/grant\s+usage\s+on\s+schema\s+private/i)})
  it('uses only Polish user-facing copy and reports deletion failures in Polish',()=>{for(const text of ['Trwale usunąć opłatę cykliczną?','Czy na pewno chcesz trwale usunąć opłatę','Usunięte zostaną','Tej operacji nie można cofnąć.','Anuluj','Usuń trwale','Usuwanie…'])expect(modal).toContain(text);expect(repository).toContain('Nie udało się trwale usunąć opłaty cyklicznej.');expect(modal).toContain('role="alert"')})
})
