import { useState, type FormEvent } from 'react'
import { Home, X } from 'lucide-react'
import { getSupabaseClient } from '../../../lib/supabase'

export function CreateFamilyModal({ displayName, onCreated, onClose }: { displayName:string; onCreated:(id:string)=>void; onClose:()=>void }) {
  const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null)
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError(null);const {data,error:rpcError}=await getSupabaseClient()!.rpc('create_additional_family',{family_name:name,owner_display_name:displayName});setBusy(false);if(rpcError){setError(rpcError.message);return}onCreated(data as string)}
  return <div className="fixed inset-0 z-[90] grid place-items-end bg-black/70 sm:place-items-center sm:p-5"><section role="dialog" aria-modal="true" aria-label="Utwórz rodzinę" className="surface w-full rounded-t-3xl p-5 sm:max-w-md sm:rounded-3xl"><header className="flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><Home className="h-4 w-4 text-brand-gold"/>Nowa rodzina</div><button onClick={onClose} aria-label="Zamknij" className="grid h-10 w-10 place-items-center"><X className="h-4 w-4"/></button></header><form onSubmit={(event)=>void submit(event)} className="mt-5 space-y-4"><label className="block text-xs text-brand-muted">Nazwa rodziny<input required minLength={2} maxLength={80} value={name} onChange={(event)=>setName(event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-brand-text outline-none focus:border-brand-gold/40"/></label>{error?<p role="alert" className="text-xs text-red-300">{error}</p>:null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-white/10 px-4">Anuluj</button><button disabled={busy} className="min-h-11 rounded-xl bg-brand-gold px-4 font-semibold text-black disabled:opacity-50">{busy?'Tworzenie…':'Utwórz rodzinę'}</button></div></form></section></div>
}
