import { useCallback, useEffect, useMemo, useState } from 'react'
import { createBudgetRepository } from '../api/budget-repository'
import { budgetSummary, monthRange } from '../budget-utils'
import { calculateSettlementBalances, calculateSuggestedTransfers } from '../settlement-utils'
import type { BudgetMember, BudgetPlan, BudgetSettlement, BudgetTransaction, ExpenseParticipant, PlanInput, SettlementInput, TransactionInput } from '../types'

export function useBudget(familyId:string,month:Date,allTime=false){
  const repository=useMemo(()=>createBudgetRepository(),[]);const[transactions,setTransactions]=useState<BudgetTransaction[]>([]);const[participants,setParticipants]=useState<ExpenseParticipant[]>([]);const[settlements,setSettlements]=useState<BudgetSettlement[]>([]);const[plans,setPlans]=useState<BudgetPlan[]>([]);const[members,setMembers]=useState<BudgetMember[]>([]);const[eligible,setEligible]=useState<BudgetMember[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null)
  const range=useMemo(()=>monthRange(month),[month]);const monthKey=range.start
  const refresh=useCallback(async()=>{setLoading(true);setError(null);try{const[t,p,s,pl,m,e]=await Promise.all([repository.listBudgetTransactions(familyId,allTime?undefined:range.start,allTime?undefined:range.end),repository.listExpenseParticipants(familyId),repository.listSettlements(familyId,allTime?undefined:range.start,allTime?undefined:range.end),repository.listBudgetPlans(familyId,monthKey),repository.listSettlementMembers(familyId),repository.listEligibleMembers(familyId)]);setTransactions(t);setParticipants(p);setSettlements(s);setPlans(pl);setEligible(e);setMembers(m.map(x=>({...x,role:e.find(y=>y.id===x.id)?.role??x.role})))}catch(reason){setError(reason instanceof Error?reason.message:'Nie udało się pobrać budżetu.')}finally{setLoading(false)}},[allTime,familyId,monthKey,range.end,range.start,repository])
  useEffect(()=>{void refresh()},[refresh]);useEffect(()=>{const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus)},[refresh])
  async function mutate(action:()=>Promise<void>){setSaving(true);setError(null);try{await action();await refresh()}catch(reason){const message=reason instanceof Error?reason.message:'Operacja nie powiodła się.';setError(message);throw new Error(message)}finally{setSaving(false)}}
  const balances=useMemo(()=>calculateSettlementBalances(transactions,participants,settlements),[participants,settlements,transactions]);const suggestions=useMemo(()=>calculateSuggestedTransfers(balances),[balances]);const summary=useMemo(()=>budgetSummary(transactions,plans),[plans,transactions])
  return{transactions,participants,settlements,plans,members,eligible,loading,saving,error,summary,balances,suggestions,refresh,
    saveTransaction:(input:TransactionInput,id?:string)=>mutate(()=>id?repository.updateBudgetTransaction(id,input):repository.createBudgetTransaction(input)),deleteTransaction:(id:string)=>mutate(()=>repository.deleteBudgetTransaction(familyId,id)),
    saveSettlement:(input:SettlementInput,id?:string)=>mutate(()=>id?repository.updateSettlement(id,input):repository.createSettlement(input)),deleteSettlement:(id:string)=>mutate(()=>repository.deleteSettlement(familyId,id)),
    savePlan:(input:PlanInput,id?:string)=>mutate(()=>id?repository.updateBudgetPlan(id,input):repository.createBudgetPlan(input)),deletePlan:(id:string)=>mutate(()=>repository.deleteBudgetPlan(familyId,id)),
    saveMembers:(ids:string[])=>mutate(()=>repository.updateSettlementMembers(familyId,members,ids))}
}

export function useBudgetPreview(familyId:string){const repository=useMemo(()=>createBudgetRepository(),[]);const[data,setData]=useState({expenses:0,plan:0,loading:true,error:null as string|null});useEffect(()=>{let cancelled=false;const range=monthRange(new Date());void Promise.all([repository.listBudgetTransactions(familyId,range.start,range.end),repository.listBudgetPlans(familyId,range.start)]).then(([items,plans])=>{if(!cancelled){const s=budgetSummary(items,plans);setData({expenses:s.expenses,plan:s.plan,loading:false,error:null})}}).catch((r:unknown)=>{if(!cancelled)setData(v=>({...v,loading:false,error:r instanceof Error?r.message:'Błąd budżetu'}))});return()=>{cancelled=true}},[familyId,repository]);return data}
