import { useState } from 'react'
import { BellOff, CheckCheck, Clock3, Trash2, X } from 'lucide-react'
import { formatNotificationDate, groupNotifications } from '../notification-utils'
import type { AppNotification, NotificationPreferences, Reminder } from '../types'
import type { SystemPushPermission } from '../native-push'
import { NotificationPreferences as PreferencesForm } from './NotificationPreferences'
import { SwipeableNotificationItem } from './SwipeableNotificationItem'

interface Props { notifications: AppNotification[]; reminders: Reminder[]; preferences: NotificationPreferences; systemPushPermission: SystemPushPermission; loading: boolean; saving: boolean; error: string | null; onOpen: (notification: AppNotification) => void; onToggleRead: (notification: AppNotification) => void; onMarkAllRead: () => void; onDismiss: (notification: AppNotification) => void; onDismissRead: () => void; onEditReminder: (reminder: Reminder) => void; onDeleteReminder: (id: string) => void; onPreferences: (value: NotificationPreferences) => void; onClose: () => void }
const sections=[{key:'new' as const,label:'Nowe'},{key:'today' as const,label:'Dzisiaj'},{key:'earlier' as const,label:'Wcześniejsze'}]

export function NotificationCenter(props: Props) {
  const groups=groupNotifications(props.notifications)
  const [confirmDismissRead,setConfirmDismissRead]=useState(false)
  const hasRead=props.notifications.some(item=>item.readAt!==null)
  return <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" onMouseDown={props.onClose}>
    <aside role="dialog" aria-modal="true" aria-label="Centrum powiadomień" onMouseDown={event=>event.stopPropagation()} className="ml-auto h-full w-full max-w-lg overflow-y-auto border-l border-white/10 bg-brand-bg p-4 shadow-2xl sm:p-6">
      <header className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-brand-gold">Centrum</p><h2 className="text-xl font-semibold">Powiadomienia</h2></div><button type="button" onClick={props.onClose} aria-label="Zamknij" className="rounded-xl p-2 text-brand-muted hover:bg-white/5"><X className="h-5 w-5"/></button></header>
      <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={props.saving||props.notifications.every(item=>item.readAt)} onClick={props.onMarkAllRead} className="inline-flex items-center gap-2 rounded-xl border border-brand-gold/20 px-3 py-2 text-xs text-brand-gold disabled:opacity-40"><CheckCheck className="h-4 w-4"/>Oznacz wszystkie jako przeczytane</button><button type="button" disabled={props.saving||!hasRead} onClick={()=>setConfirmDismissRead(true)} className="inline-flex items-center gap-2 rounded-xl border border-red-400/15 px-3 py-2 text-xs text-red-300 disabled:opacity-40"><Trash2 className="h-4 w-4"/>Usuń przeczytane</button></div>
      {props.error?<p role="alert" className="mt-4 rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-xs text-red-300">{props.error}</p>:null}
      {props.loading?<div className="mt-5 h-40 animate-pulse rounded-2xl bg-white/[.03]"/>:null}
      {!props.loading&&props.notifications.length===0?<div className="mt-5 rounded-2xl border border-white/5 p-8 text-center"><BellOff className="mx-auto h-6 w-6 text-brand-muted"/><p className="mt-3 text-sm">Brak powiadomień</p></div>:null}
      {!props.loading?sections.map(section=>groups[section.key].length?<section key={section.key} className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-[.14em] text-brand-muted">{section.label}</h3><div className="mt-2 space-y-2">{groups[section.key].map(item=><SwipeableNotificationItem key={item.id} item={item} saving={props.saving} onOpen={()=>props.onOpen(item)} onToggleRead={()=>props.onToggleRead(item)} onDismiss={()=>props.onDismiss(item)}/>)}</div></section>:null):null}
      <section className="mt-8 border-t border-white/5 pt-6"><h3 className="text-sm font-semibold">Nadchodzące przypomnienia</h3>{props.reminders.length===0?<p className="mt-2 text-xs text-brand-muted">Nie masz aktywnych przypomnień.</p>:<div className="mt-3 space-y-2">{props.reminders.map(item=><div key={item.id} className="rounded-xl border border-white/5 p-3"><p className="text-sm">{item.title??'Przypomnienie'}</p><p className="mt-1 inline-flex items-center gap-1 text-[11px] text-brand-muted"><Clock3 className="h-3 w-3"/>{formatNotificationDate(item.remindAt)}</p>{item.kind==='personal'?<div className="mt-2 flex gap-3 text-[10px]"><button type="button" onClick={()=>props.onEditReminder(item)} className="text-brand-gold">Zmień</button><button type="button" onClick={()=>props.onDeleteReminder(item.id)} className="text-red-300">Usuń</button></div>:<p className="mt-2 text-[10px] text-brand-muted">Przypomnienie zadania zarządzane przez autora lub administratora.</p>}</div>)}</div>}</section>
      <div className="mt-8 border-t border-white/5 pt-6"><PreferencesForm value={props.preferences} saving={props.saving} systemPermission={props.systemPushPermission} onChange={props.onPreferences}/></div>
    </aside>
    {confirmDismissRead?<div className="fixed inset-0 z-[60] grid place-items-end bg-black/70 p-0 sm:place-items-center sm:p-4" onMouseDown={event=>event.stopPropagation()}><section role="alertdialog" aria-modal="true" className="surface w-full rounded-t-3xl p-5 sm:max-w-md sm:rounded-3xl"><h3 className="font-semibold">Usunąć przeczytane powiadomienia?</h3><p className="mt-2 text-xs text-brand-muted">Znikną z Centrum powiadomień. Obiekty źródłowe i historia wysyłki push pozostaną bez zmian.</p><div className="mt-5 flex justify-end gap-2"><button type="button" disabled={props.saving} onClick={()=>setConfirmDismissRead(false)} className="min-h-11 rounded-xl border border-white/10 px-4">Anuluj</button><button type="button" disabled={props.saving} onClick={()=>{props.onDismissRead();setConfirmDismissRead(false)}} className="min-h-11 rounded-xl bg-red-500/80 px-4 font-semibold text-white disabled:opacity-50">Usuń przeczytane</button></div></section></div>:null}
  </div>
}
