import { useEffect, useState, type FormEvent } from 'react'
import { BellRing, X } from 'lucide-react'
import { toDateTimeLocal } from '../notification-utils'
import type { Reminder, ReminderSource } from '../types'

interface Props { source: ReminderSource; reminder?: Reminder; saving: boolean; error: string | null; onSave: (source: ReminderSource, remindAt: string, timezone: string, existingId?: string) => Promise<void>; onDelete: (id: string) => Promise<void>; onClose: () => void }

export function ReminderModal({ source, reminder, saving, error, onSave, onDelete, onClose }: Props) {
  const [date, setDate] = useState(() => toDateTimeLocal(reminder?.remindAt ?? source.occursAt))
  const [validation, setValidation] = useState<string | null>(null)
  useEffect(() => setDate(toDateTimeLocal(reminder?.remindAt ?? source.occursAt)), [reminder?.remindAt, source.occursAt])
  async function submit(event: FormEvent) { event.preventDefault(); const parsed = new Date(date); if (!date || Number.isNaN(parsed.getTime()) || parsed <= new Date()) { setValidation('Wybierz termin w przyszłości.'); return } setValidation(null); await onSave(source, parsed.toISOString(), Intl.DateTimeFormat().resolvedOptions().timeZone, reminder?.id); onClose() }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><form onSubmit={(event) => void submit(event)} className="surface w-full max-w-md rounded-2xl p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-brand-gold">Osobiste przypomnienie</p><h2 className="mt-1 text-lg font-semibold">{source.title}</h2></div><button type="button" onClick={onClose} aria-label="Zamknij" className="rounded-lg p-1.5 text-brand-muted hover:bg-white/5"><X className="h-4 w-4"/></button></div><label className="mt-5 block text-xs text-brand-muted">Data i godzina<input type="datetime-local" required value={date} onChange={(event) => setDate(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2.5 text-sm text-brand-text outline-none focus:border-brand-gold/40"/></label><p className="mt-2 text-[11px] text-brand-muted">Strefa: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Przypomnienie przetwarza backend — aplikacja nie musi być otwarta.</p>{validation || error ? <p role="alert" className="mt-3 text-xs text-red-300">{validation ?? error}</p> : null}<div className="mt-5 flex flex-wrap justify-end gap-2">{reminder ? <button type="button" disabled={saving} onClick={() => void onDelete(reminder.id).then(onClose)} className="mr-auto rounded-xl border border-red-400/20 px-3 py-2 text-xs text-red-300 disabled:opacity-50">Usuń</button> : null}<button type="button" disabled={saving} onClick={onClose} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-brand-muted">Anuluj</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-brand-gold px-4 py-2 text-xs font-semibold text-black disabled:opacity-50"><BellRing className="h-3.5 w-3.5"/>{saving ? 'Zapisywanie…' : reminder ? 'Zmień' : 'Ustaw przypomnienie'}</button></div></form></div>
}
