import { getSupabaseClient } from '../../../lib/supabase'
import type { FamilyRole } from '../../../types/domain'
import { centsToDatabase } from '../budget-utils'
import type { BudgetMember, BudgetPlan, BudgetSettlement, BudgetTransaction, ExpenseParticipant, PlanInput, SettlementInput, TransactionInput } from '../types'

type Profile = { id:string; display_name:string } | Array<{id:string;display_name:string}> | null
const profile = (value:Profile,id:string) => { const p=Array.isArray(value)?value[0]:value; return p?{id:p.id,displayName:p.display_name}:{id,displayName:'Nieaktywny użytkownik'} }
const client=()=>{const value=getSupabaseClient();if(!value)throw new Error('Brak konfiguracji Supabase.');return value}
const txSelect=`id,family_id,transaction_type,title,description,amount,currency,category,transaction_date,paid_by,is_shared,created_by,created_at,payer:profiles!budget_transactions_paid_by_fkey(id,display_name),creator:profiles!budget_transactions_created_by_fkey(id,display_name)`
const settlementSelect=`id,family_id,from_user_id,to_user_id,amount,currency,settlement_date,note,created_by,from_user:profiles!budget_settlements_from_user_id_fkey(id,display_name),to_user:profiles!budget_settlements_to_user_id_fkey(id,display_name),creator:profiles!budget_settlements_created_by_fkey(id,display_name)`
interface TxRow {id:string;family_id:string;transaction_type:BudgetTransaction['type'];title:string;description:string|null;amount:string|number;currency:string;category:string|null;transaction_date:string;paid_by:string|null;is_shared:boolean;created_by:string;created_at:string;payer:Profile;creator:Profile}
interface SettlementRow {id:string;family_id:string;from_user_id:string;to_user_id:string;amount:string|number;currency:string;settlement_date:string;note:string|null;created_by:string;from_user:Profile;to_user:Profile;creator:Profile}
const mapTx=(r:TxRow):BudgetTransaction=>({id:r.id,familyId:r.family_id,type:r.transaction_type,title:r.title,description:r.description,amountCents:Math.round(Number(r.amount)*100),currency:r.currency,category:r.category,date:r.transaction_date,paidBy:r.paid_by?profile(r.payer,r.paid_by):null,shared:r.is_shared,createdBy:profile(r.creator,r.created_by),createdAt:r.created_at})
const payload=(i:TransactionInput)=>({family_id:i.familyId,transaction_type:i.type,title:i.title.trim(),description:i.description.trim()||null,amount:centsToDatabase(i.amountCents),currency:'PLN',category:i.category.trim()||null,transaction_date:i.date,paid_by:i.type==='expense'?i.paidById:null,is_shared:i.type==='expense'&&i.shared})
const updatePayload=(i:TransactionInput)=>{const{family_id:_,...values}=payload(i);void _;return values}

export function createBudgetRepository(){return{
  async listBudgetTransactions(familyId:string,start?:string,end?:string){let q=client().from('budget_transactions').select(txSelect).eq('family_id',familyId).order('transaction_date',{ascending:false}).order('created_at',{ascending:false});if(start)q=q.gte('transaction_date',start);if(end)q=q.lt('transaction_date',end);const{data,error}=await q;if(error)throw new Error(error.message);return((data??[])as unknown as TxRow[]).map(mapTx)},
  async createBudgetTransaction(i:TransactionInput){const{error}=await client().from('budget_transactions').insert(payload(i));if(error)throw new Error(error.message)},
  async updateBudgetTransaction(id:string,i:TransactionInput){const{data,error}=await client().from('budget_transactions').update(updatePayload(i)).eq('family_id',i.familyId).eq('id',id).select('id').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Nie masz uprawnień do edycji transakcji.')},
  async deleteBudgetTransaction(familyId:string,id:string){const{data,error}=await client().from('budget_transactions').delete().eq('family_id',familyId).eq('id',id).select('id').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Nie masz uprawnień do usunięcia transakcji.')},
  async listExpenseParticipants(familyId:string){const{data,error}=await client().from('budget_expense_participants').select('transaction_id,user_id,share_weight,user:profiles!budget_expense_participants_user_id_fkey(id,display_name)').eq('family_id',familyId);if(error)throw new Error(error.message);return((data??[])as unknown as Array<{transaction_id:string;user_id:string;share_weight:number|string;user:Profile}>).map((r):ExpenseParticipant=>({transactionId:r.transaction_id,user:profile(r.user,r.user_id),shareWeight:Number(r.share_weight)}))},
  async listSettlementMembers(familyId:string){const{data,error}=await client().from('budget_settlement_members').select('user_id,is_active,user:profiles!budget_settlement_members_user_id_fkey(id,display_name)').eq('family_id',familyId);if(error)throw new Error(error.message);return((data??[])as unknown as Array<{user_id:string;is_active:boolean;user:Profile}>).map((r):BudgetMember=>({...profile(r.user,r.user_id),role:'adult',active:r.is_active}))},
  async listEligibleMembers(familyId:string){const{data,error}=await client().from('family_members').select('user_id,display_name,role,status').eq('family_id',familyId).eq('status','active').in('role',['owner','admin','adult']).order('display_name');if(error)throw new Error(error.message);return((data??[])as Array<{user_id:string;display_name:string;role:FamilyRole}>).map((r):BudgetMember=>({id:r.user_id,displayName:r.display_name,role:r.role,active:false}))},
  async updateSettlementMembers(familyId:string,current:BudgetMember[],selected:string[]){const existing=new Set(current.map(x=>x.id));for(const member of current){const{error}=await client().from('budget_settlement_members').update({is_active:selected.includes(member.id)}).eq('family_id',familyId).eq('user_id',member.id);if(error)throw new Error(error.message)}for(const id of selected.filter(x=>!existing.has(x))){const{error}=await client().from('budget_settlement_members').insert({family_id:familyId,user_id:id,is_active:true});if(error)throw new Error(error.message)}},
  async listSettlements(familyId:string,start?:string,end?:string){let q=client().from('budget_settlements').select(settlementSelect).eq('family_id',familyId).order('settlement_date',{ascending:false});if(start)q=q.gte('settlement_date',start);if(end)q=q.lt('settlement_date',end);const{data,error}=await q;if(error)throw new Error(error.message);return((data??[])as unknown as SettlementRow[]).map((r):BudgetSettlement=>({id:r.id,familyId:r.family_id,from:profile(r.from_user,r.from_user_id),to:profile(r.to_user,r.to_user_id),amountCents:Math.round(Number(r.amount)*100),currency:r.currency,date:r.settlement_date,note:r.note,createdBy:profile(r.creator,r.created_by)}))},
  async createSettlement(i:SettlementInput){const{error}=await client().from('budget_settlements').insert({family_id:i.familyId,from_user_id:i.fromUserId,to_user_id:i.toUserId,amount:centsToDatabase(i.amountCents),currency:'PLN',settlement_date:i.date,note:i.note.trim()||null});if(error)throw new Error(error.message)},
  async updateSettlement(id:string,i:SettlementInput){const{data,error}=await client().from('budget_settlements').update({from_user_id:i.fromUserId,to_user_id:i.toUserId,amount:centsToDatabase(i.amountCents),settlement_date:i.date,note:i.note.trim()||null}).eq('family_id',i.familyId).eq('id',id).select('id').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Nie masz uprawnień do edycji rozliczenia.')},
  async deleteSettlement(familyId:string,id:string){const{data,error}=await client().from('budget_settlements').delete().eq('family_id',familyId).eq('id',id).select('id').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Nie masz uprawnień do usunięcia rozliczenia.')},
  async listBudgetPlans(familyId:string,month:string){const{data,error}=await client().from('budget_plans').select('id,family_id,month,plan_type,category,amount,currency').eq('family_id',familyId).eq('month',month);if(error)throw new Error(error.message);return((data??[])as Array<{id:string;family_id:string;month:string;plan_type:BudgetPlan['type'];category:string|null;amount:string|number;currency:string}>).map((r):BudgetPlan=>({id:r.id,familyId:r.family_id,month:r.month,type:r.plan_type,category:r.category,amountCents:Math.round(Number(r.amount)*100),currency:r.currency}))},
  async createBudgetPlan(i:PlanInput){const{error}=await client().from('budget_plans').insert({family_id:i.familyId,month:i.month,plan_type:i.type,category:i.category.trim()||null,amount:centsToDatabase(i.amountCents),currency:'PLN'});if(error)throw new Error(error.message)},
  async updateBudgetPlan(id:string,i:PlanInput){const{error}=await client().from('budget_plans').update({month:i.month,plan_type:i.type,category:i.category.trim()||null,amount:centsToDatabase(i.amountCents),currency:'PLN'}).eq('family_id',i.familyId).eq('id',id);if(error)throw new Error(error.message)},
  async deleteBudgetPlan(familyId:string,id:string){const{error}=await client().from('budget_plans').delete().eq('family_id',familyId).eq('id',id);if(error)throw new Error(error.message)},
}}
