import{readFileSync}from'node:fs'
import{resolve}from'node:path'
import{describe,expect,it}from'vitest'
const sql=readFileSync(resolve(process.cwd(),'../../database/migrations/0022_family_data_export.sql'),'utf8')
describe('0022 family data export security contract',()=>{
 it('uses an explicit deterministic module allowlist and rejects unknown modules',()=>{for(const module of ['family','members','tasks','calendar','shopping','budget','fixedCharges','reminders'])expect(sql).toContain(`'${module}'`);expect(sql).toContain("raise exception 'unknown export module'");expect(sql).toContain('array_agg(module_name order by position)')})
 it('rejects an empty module request',()=>{expect(sql).toContain("selected_modules is null or pg_catalog.cardinality(selected_modules)=0");expect(sql).toContain("raise exception 'select at least one export module'")})
 it('implicitly prepends family and deterministically deduplicates requested modules',()=>{expect(sql).toContain("where module_name='family' or module_name=any(selected_modules)");expect(sql).toContain('array_agg(module_name order by position)');const allowed=['family','members','tasks','calendar','shopping','budget','fixedCharges','reminders'];const normalize=(selected:string[])=>allowed.filter(module=>module==='family'||selected.includes(module));expect(normalize(['tasks'])).toEqual(['family','tasks']);expect(normalize(['tasks','family','tasks'])).toEqual(['family','tasks'])})
 it('allows only active owner or admin through the existing server-side role helper',()=>{expect(sql).toContain("public.has_family_role(target_family_id,array['owner','admin']::public.family_role[])");expect(sql).toContain("raise exception 'family export requires an active owner or admin'")})
 it('builds exported business data in one main statement before audit',()=>{const payloadStart=sql.indexOf('with export_data as');const audit=sql.indexOf('insert into public.audit_logs');expect(payloadStart).toBeGreaterThan(0);expect(audit).toBeGreaterThan(payloadStart);expect(sql.slice(payloadStart,audit)).toContain('select pg_catalog.jsonb_build_object')})
 it('filters every exported family relation by target family',()=>{for(const table of ['family_members','tasks','task_recurrence_series','calendar_events','shopping_lists','shopping_items','budget_transactions','budget_expense_participants','budget_settlement_members','budget_settlements','budget_plans','properties','property_units','property_charge_definitions','property_charge_schedule_dates','property_charge_reminder_rules','property_charges','reminders','notification_preferences'])expect(sql).toMatch(new RegExp(`from public\\.${table}[^;]+family_id=target_family_id`))})
 it('never exports authentication, email, devices, notifications, platform or private data',()=>{for(const forbidden of ['auth.users','auth.identities','push_token','notification_devices','notification_push_deliveries','notification_device_credentials','platform_admins','platform_audit_logs','vault.decrypted_secrets'])expect(sql).not.toContain(forbidden);expect(sql).not.toMatch(/select[^;]*email/i)})
 it('exports reminders only for auth.uid and labels their scope',()=>{expect(sql).toContain('r.recipient_user_id=current_user_id');expect(sql).toContain('p.user_id=current_user_id');expect(sql).toContain("'scope','current_user'")})
 it('preserves fixed-charge relationships without duplicating budget rows',()=>{for(const key of ['definitions','scheduleDates','reminderRules','charges'])expect(sql).toContain(`'${key}'`);expect(sql).toContain('as "budgetTransactionId"');expect(sql.match(/from public\.budget_transactions/g)).toHaveLength(1)})
 it('always includes a valid family manifest and family record count',()=>{expect(sql).toContain("'family',family_data");expect(sql).toContain("'family',1");expect(sql).toContain("raise exception 'target family does not exist'");expect(sql).not.toContain("'family',case when 'family'=any(normalized_modules)")})
 it('represents selected empty modules and omits unselected optional modules',()=>{expect(sql).toContain("'[]'::jsonb");expect(sql).toContain('jsonb_strip_nulls');expect(sql).toContain("case when 'tasks'=any(normalized_modules)")})
 it('reports counts and fails explicitly above the 8 MiB synchronous limit',()=>{expect(sql).toContain("'recordCounts',counts");expect(sql).toContain('maximum_payload_bytes constant integer := 8388608');expect(sql).toContain('family export exceeds the 8 MiB synchronous export limit')})
 it('audits metadata only and exposes only the narrow RPC',()=>{expect(sql).toContain("'family.backup.exported'");expect(sql).toContain("'recordCounts',payload->'recordCounts'");expect(sql).not.toContain("'exportedData'");expect(sql).toContain('security definer');expect(sql).toContain("set search_path = ''");expect(sql).toContain('revoke all on function public.export_family_data(uuid,text[]) from public,anon,authenticated');expect(sql).toContain('grant execute on function public.export_family_data(uuid,text[]) to authenticated')})
})
