import{useMemo,useState,type ChangeEvent}from'react';import{AlertTriangle,RotateCcw}from'lucide-react';import type{FamilyContext,FamilyMember}from'../../../types/domain';import type{BackupPayload,RestoreModule,RestoreUserMapping}from'../types';import{availableRestoreModules,readBackupFile,requiredSourceUsers,restoreErrorMessage,restoreLabels,sourceUserLabel,sourceUsers}from'../restore-utils';import{useBackupRestore}from'../hooks/useBackupRestore'

const steps=['Wybierz kopię','Sprawdzenie kopii','Wybierz moduły','Mapowanie użytkowników','Podsumowanie zmian','Potwierdzenie','Przywracanie','Wynik'];
export function BackupRestoreWizard({family,members,onRestored}:{family:FamilyContext;members:FamilyMember[];onRestored:()=>void}){const[open,setOpen]=useState(false),[step,setStep]=useState(0),[backup,setBackup]=useState<BackupPayload|null>(null),[modules,setModules]=useState<RestoreModule[]>([]),[mapping,setMapping]=useState<RestoreUserMapping>({}),[confirmation,setConfirmation]=useState(''),[fileError,setFileError]=useState<string|null>(null);const state=useBackupRestore(family.familyId,onRestored);const users=useMemo(()=>backup?sourceUsers(backup,modules):[],[backup,modules]);const requiredUsers=useMemo(()=>backup?requiredSourceUsers(backup,modules):new Set<string>(),[backup,modules]);const activeMembers=members.filter(member=>member.status==='active');
 function reset(){setStep(0);setBackup(null);setModules([]);setMapping({});setConfirmation('');setFileError(null);state.clear()}
 async function choose(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setFileError(null);try{const parsed=await readBackupFile(file);const available=availableRestoreModules(parsed);setBackup(parsed);setModules(available);setMapping({});setStep(1)}catch(error){setFileError(error instanceof Error?error.message:'Nie udało się odczytać kopii.')}}
 function toggle(module:RestoreModule){setModules(current=>current.includes(module)?current.filter(value=>value!==module):[...current,module])}
 async function preflight(){if(!backup)return;const report=await state.check(backup,modules,mapping);setStep(report.valid?4:3)}
 async function restore(){if(!backup)return;setStep(6);try{await state.restore(backup,modules,mapping,confirmation);setStep(7);window.setTimeout(()=>window.location.reload(),1500)}catch{setStep(5)}}
 if(family.role!=='owner')return null;
 if(!open)return <button onClick={()=>setOpen(true)} className="mt-3 min-h-11 w-full rounded-xl border border-red-400/20 px-4 text-sm text-red-200"><RotateCcw className="mr-2 inline h-4 w-4"/>Przywróć kopię</button>;
 return <div className="mt-4 rounded-2xl border border-red-400/20 bg-black/20 p-3 sm:p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="text-sm font-semibold">Przywróć kopię</h4><p className="mt-1 text-[10px] text-brand-muted">Krok {step+1}/8 · {steps[step]}</p></div><button disabled={state.busy} onClick={()=>{reset();setOpen(false)}} className="min-h-11 px-2 text-xs text-brand-muted">Zamknij</button></div>
 {step===0?<div className="mt-3"><p className="text-xs leading-relaxed text-brand-muted">Dane wybranych modułów zostaną zastąpione atomowo. Rodzina, członkowie i ustawienia powiadomień nie zostaną zmienione.</p><input aria-label="Plik kopii JSON" accept="application/json,.json" type="file" onChange={event=>void choose(event)} className="mt-3 block w-full text-xs file:mr-2 file:min-h-11 file:rounded-xl file:border-0 file:bg-brand-gold file:px-3 file:font-semibold file:text-black"/>{fileError?<p role="alert" className="mt-2 text-xs text-red-300">{fileError}</p>:null}</div>:null}
 {step===1&&backup?<div className="mt-3 text-xs"><p><span className="text-brand-muted">Źródło:</span> {backup.family.name}</p><p><span className="text-brand-muted">Data:</span> {new Date(backup.createdAt).toLocaleString('pl-PL')}</p><button onClick={()=>setStep(2)} className="mt-3 min-h-11 w-full rounded-xl bg-brand-gold font-semibold text-black">Wybierz moduły</button></div>:null}
 {step===2&&backup?<div className="mt-3"><div className="grid grid-cols-2 gap-1.5">{availableRestoreModules(backup).map(module=><label key={module} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-2 text-[11px]"><input type="checkbox" checked={modules.includes(module)} onChange={()=>toggle(module)}/>{restoreLabels[module]}</label>)}</div><button disabled={!modules.length} onClick={()=>setStep(3)} className="mt-3 min-h-11 w-full rounded-xl bg-brand-gold font-semibold text-black disabled:opacity-40">Mapuj użytkowników</button></div>:null}
 {step===3&&backup?<div className="mt-3 space-y-2">{users.map(id=><label key={id} className="block text-[11px] text-brand-muted">{sourceUserLabel(backup,id)}{requiredUsers.has(id)?' · wymagane':''}<select aria-label={`Mapowanie ${id}`} value={mapping[id]??''} onChange={event=>setMapping(current=>({...current,[id]:event.target.value}))} className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-[#101017] px-3 text-sm text-brand-text"><option value="">Wybierz członka…</option>{!requiredUsers.has(id)?<option value="none">Brak (tylko pola opcjonalne)</option>:null}{activeMembers.map(member=><option key={member.userId} value={member.userId}>{member.displayName} · {member.role}</option>)}</select></label>)}{state.error?<p role="alert" className="text-xs text-red-300">{state.error}</p>:null}{state.preflight&&!state.preflight.valid?<ul className="text-xs text-red-300">{state.preflight.errors.map(value=><li key={value} data-error-code={value}>{restoreErrorMessage(value)}</li>)}</ul>:null}<button disabled={state.busy||users.some(id=>!mapping[id]||(requiredUsers.has(id)&&mapping[id]==='none'))} onClick={()=>void preflight()} className="min-h-11 w-full rounded-xl bg-brand-gold font-semibold text-black disabled:opacity-40">{state.busy?'Sprawdzanie…':'Sprawdź na serwerze'}</button></div>:null}
 {step===4&&state.preflight?<div className="mt-3 text-xs"><p><b>{state.preflight.source?.familyName}</b> → <b>{state.preflight.destination?.familyName}</b></p><p className="mt-2 text-brand-muted">Wybrane: {state.preflight.normalizedModules.map(module=>restoreLabels[module]).join(', ')}</p><pre className="mt-2 max-h-32 overflow-auto whitespace-pre-wrap rounded-xl bg-black/30 p-2 text-[10px]">Do usunięcia: {JSON.stringify(state.preflight.recordsToRemove,null,2)}</pre>{state.preflight.warnings.map(value=><p key={value} className="mt-1 text-amber-200">⚠ {value}</p>)}<button onClick={()=>setStep(5)} className="mt-3 min-h-11 w-full rounded-xl bg-red-300 font-semibold text-black">Przejdź do potwierdzenia</button></div>:null}
 {step===5?<div className="mt-3"><p className="flex gap-2 text-xs text-red-200"><AlertTriangle className="h-4 w-4 shrink-0"/>Ta operacja bezpowrotnie zastąpi dane wybranych modułów. Trwającej transakcji nie można anulować.</p><label className="mt-3 block text-[11px] text-brand-muted">Wpisz: {family.familyName}<input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-brand-text"/></label><button disabled={confirmation!==family.familyName||state.busy} onClick={()=>void restore()} className="mt-3 min-h-11 w-full rounded-xl bg-red-400 font-semibold text-black disabled:opacity-40">Przywróć i zastąp dane</button></div>:null}
 {step===6?<p role="status" className="mt-4 text-sm">Przywracanie trwa. Nie zamykaj aplikacji…</p>:null}
 {step===7&&state.result?<div className="mt-4"><p className="text-sm text-emerald-300">Kopia została przywrócona.</p><p className="mt-1 text-[10px] text-brand-muted">Operacja: {state.result.operationId}</p><button onClick={reset} className="mt-3 min-h-11 w-full rounded-xl border border-white/10">Gotowe</button></div>:null}</div>}
