import { CalendarDays, MapPin } from 'lucide-react'
import { formatEventTime } from '../calendar-utils'
import { useUpcomingCalendarEvents } from '../hooks/useCalendar'

interface Props { familyId: string; onViewCalendar: () => void }

export function UpcomingEventsCard({ familyId, onViewCalendar }: Props) {
  const { events, loading, error } = useUpcomingCalendarEvents(familyId)
  return <article className="surface overflow-hidden rounded-2xl"><header className="flex items-center justify-between border-b border-white/5 px-5 py-4"><h2 className="font-semibold">Najbliższe wydarzenia</h2><button type="button" onClick={onViewCalendar} className="text-xs font-medium text-brand-gold hover:underline">Zobacz kalendarz</button></header>{loading ? <div className="space-y-3 p-5" aria-label="Ładowanie wydarzeń"><div className="h-14 animate-pulse rounded-xl bg-white/[.035]"/><div className="h-14 animate-pulse rounded-xl bg-white/[.035]"/></div> : null}{!loading && error ? <p role="alert" className="m-5 rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-sm text-red-300">Nie udało się pobrać wydarzeń: {error}</p> : null}{!loading && !error && events.length === 0 ? <div className="p-8 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-full bg-brand-gold/10 text-brand-gold"><CalendarDays className="h-5 w-5"/></div><p className="mt-3 text-sm font-medium">Nie masz jeszcze żadnych wydarzeń rodzinnych.</p><button type="button" onClick={onViewCalendar} className="mt-2 text-xs text-brand-gold hover:underline">Otwórz kalendarz</button></div> : null}{!loading && !error && events.length ? <div className="divide-y divide-white/5">{events.map((event) => <button key={event.id} type="button" onClick={onViewCalendar} className="flex w-full items-start gap-3 px-5 py-4 text-left hover:bg-white/[.025]"><CalendarDays className="mt-0.5 h-4 w-4 shrink-0 text-brand-gold"/><div className="min-w-0"><p className="truncate text-sm font-medium">{event.title}</p><p className="mt-1 flex flex-wrap gap-2 text-[11px] text-brand-muted"><span>{event.allDay ? event.startDate : event.startsAt ? new Intl.DateTimeFormat('pl-PL', { day: '2-digit', month: '2-digit' }).format(new Date(event.startsAt)) : ''} • {formatEventTime(event)}</span>{event.location ? <span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3"/>{event.location}</span> : null}</p></div></button>)}</div> : null}</article>
}
